### ISSUE TITLE
Potential table printing error

### ISSUE THREAD

**Issue by alextsigh** [MaayanLab/appyter#100]
When I'm printing tables, the first table is printed twice and the last table is not printed at all (although the download file for this last table is still present and still has the correct data). These issues are not present when I run the jupyter notebook by itself, only when I run the entire appyter.

**Comment by u8sand** [comment]
It would be helpful to have a minimum reproducible example so I can better debug this.

**Comment by alextsigh** [comment]
Below are two screenshots of the tables printing correcting in the jupyter notebook itself as well as the same tables that get printed incorrectly when I run the appyter.

In the Jupyter Notebook:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/85768439/125687492-cf275a74-421d-4e12-848c-ad92a6d785bb.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/85768439/125687522-945241f6-a21c-4900-9615-42534bff365e.png">

When I run the appyter:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/85768439/125688149-ecbed683-7ee5-4ade-aa0c-0a2c9eb1f517.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/85768439/125688175-93b39164-1fa1-4aec-b559-a082a909a782.png">

**Comment by u8sand** [comment]
I need an actual jupyter notebook in order to debug this. At the very least I'd need the source of the cell...

**Comment by u8sand** [comment]
I fixed something related to this in the latest version, please confirm whether or not your issue persists.

**Comment by u8sand** [comment]
Fixed in b7867e65ea306d6abaeb14049cdd674bf85cfcda
