### ISSUE TITLE
public_url questions

### ISSUE THREAD

**Issue by jpuerto-psc** [MaayanLab/appyter#141]
Hello All,

Hoping to get some additional guidance on the public_url configuration parameter's functionality. In our deployment, we are planning on having one machine that acts as the proxy to appyter instances that are running on individual compute/GPU nodes. Because of this, we are running into errors w/ socket.io where we get `{{ our public_url }} is not an accepted origin.`

I was hopeful that setting proxy to true and the public_url equal to the domain name of the machine that acts as the proxy would be the appropriate resolution here. Any thoughts? Is there a way to pass the acceptable origins list somewhere?

Is the public_url meant to include the scheme as well? Or just the domain name?

Best regards,

Juan

**Comment by u8sand** [comment]
Fixed in #138
