### ISSUE TITLE
Input fields do not accept variables

### ISSUE THREAD

**Issue by serena-zhang** [MaayanLab/appyter#39]
For example, if I declare and initiate my list `list`, then try to use `list` as my default for a StringField, jupyter notebook will return the issue of: `Error: undeclared variable(s) {list}`.

**Comment by u8sand** [comment]
A StringField is meant to hold a string, not a list--this is intended.

**Comment by serena-zhang** [comment]
Yes, I meant to say string `str`. The other part resolves my issue, thank you!
