### ISSUE TITLE
Markdown is misplaced

### ISSUE THREAD

**Issue by mjjeon** [MaayanLab/appyter#5]
I tried to display a markdown saying "PRE~~" on the top of the plot but it is placed on the bottom

<img width="1440" alt="스크린샷 2020-04-09 오전 11 25 21" src="https://user-images.githubusercontent.com/7698704/78912114-38160f00-7a55-11ea-9393-5cc157cbd94c.png">

**Comment by u8sand** [comment]
I can look into this but I got an error when I tried running your notebook

![image](https://user-images.githubusercontent.com/1341861/78915666-44e93180-7a5a-11ea-9c0d-9bd41e5a0c01.png)

**Comment by mjjeon** [comment]
When I run a cell that defines fields, I got an error message below. It didn't happen in the previous version. By the way, I am fixing some stuff so I am going to handle the issue you mentioned. 


meta_data_filename = "metadata.csv"
rnaseq_data_filename = "rnaseq.csv"
low_expression_threshold = 0.3
meta_class_column_name = "CLASS"
meta_id_column_name = "SAMPLE_ID"
rnaseq_normalized_output_filename = "rnaseq_normalized.csv"
log_normalization = True
z_normalization = True
q_normalization = True
clustering_topk = 800
expr_df_sub_file = "expr_df_sub_file.txt"
cd_diff_gene_topk = 600
l1000cds2_topk = 2000
Enrichr_links_filename = "Enrichr_links.xls"
L1000CDS2_links_filename = "L1000CDS2_links.xls"
Traceback (most recent call last):

  File "//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-9-b65b3b3b2fbb>", line 1, in <module>
    get_ipython().run_cell_magic('jupyter_template', 'code_eval', 'meta_data_filename = "{{ FileField(name=\'meta_data_filename\', label=\'meta_data_filename\', default=\'metadata.csv\', description=\'Upload metadata as two-column csv format. One column contains sample ids and the other column contains sample labels\').value }}"\nrnaseq_data_filename = "{{ FileField(name=\'rnaseq_data_filename\', label=\'rnaseq_data_filename\', default=\'rnaseq.csv\', description=\'Upload rna-seq dataset as csv format. The index of the dataset are genes, the columns are samples.\').value }}"\nlow_expression_threshold = {{ FloatField(name=\'low_expression_threshold\', label=\'low_expression_threshold\', default=\'0.3\', description=\'Threshold to filter out low expression genes. The value should vary based on the user dataset.\').value }}\nmeta_class_column_name = "{{ StringField(name=\'meta_class_column_name\', label=\'meta_class_column_name\', default=\'CLASS\', description=\'class column name of metadata\').value }}"\nmeta_id_column_name = "{{ StringField(name=\'meta_id_column_name\', label=\'meta_id_column_name\', default=\'SAMPLE_ID\', description=\'sample ID column name of metadata\').value }}"\nrnaseq_normalized_output_filename = "{{ StringField(name=\'rnaseq_normalized_output_filename\', label=\'rnaseq_normalized_output_filename\', default=\'rnaseq_normalized.csv\', description=\'if user wants to download the normalized dataset, please name of the output file.\').value }}"\nlog_normalization = {{ BoolField(name=\'log_normalization\', label=\'log_normalization\', default=\'true\', description=\'Check if User wants the dataset to be log-transformed\').value }}\nz_normalization = {{ BoolField(name=\'z_normalization\', label=\'z_normalization\', default=\'true\', description=\'Check if User wants the dataset to be normalized with Z-normalized method\').value }}\nq_normalization = {{ BoolField(name=\'q_normalization\', label=\'q_normalization\', default=\'true\', description=\'Check if User wants the dataset to be normalized with Quantile normalization method\').value }}\n\n\nclustering_topk = {{ IntField(name=\'clustering_topk\', label=\'clustering_topk\', default=800, description=\'The number of genes with largest variance for Clustergrammer\').value }}\nexpr_df_sub_file = "{{ StringField(name=\'expr_df_sub_file\', label=\'expr_df_sub_file\', default=\'expr_df_sub_file.txt\', description=\'Save the dataset of clustering_topk genes for Clustergrammer\').value }}"\n\ncd_diff_gene_topk = {{ IntField(name=\'cd_diff_gene_topk\', label=\'cd_diff_gene_topk\', default=600, description=\'The maximum number of genes discovered by the Characteristic Direction method\').value }}\nl1000cds2_topk = {{ IntField(name=\'l1000cds2_topk\', label=\'l1000cds2_topk\', default=2000, description=\'The number of genes to be queried to L1000CDS2\').value }}\n\nEnrichr_links_filename = "{{ StringField(name=\'Enrichr_links_filename\', label=\'Enrichr_links_filename\', default=\'Enrichr_links.xls\', description=\'The output filename of Enrichr results\').value }}"\nL1000CDS2_links_filename = "{{ StringField(name=\'L1000CDS2_links_filename\', label=\'L1000CDS2_links_filename\', default=\'L1000CDS2_links.xls\', description=\'The output filename of L1000CDS2 results\').value }}"\n')

  File "//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2362, in run_cell_magic
    result = fn(*args, **kwargs)

  File "//anaconda3/lib/python3.7/site-packages/jupyter_template/magic.py", line 71, in jupyter_template
    display(eval(rendered_last, global_internal))

  File "<string>", line 1
    L1000CDS2_links_filename = "L1000CDS2_links.xls"
                             ^
SyntaxError: invalid syntax

**Comment by u8sand** [comment]
@mjjeon I've made the jupyter template eval vs exec more predictable since I had some issues with it. If you want to `evaluate` the last line in your notebook use:

```
%jupyter_template code_eval
1+1
```

If you want to just execute it, not evaluating the last line in your notebook, use:

```
%jupyter_template code_exec
1+1
```

In the case you showed above, you'd want `code_exec` -- this is because jupyter generally executes the last line in a cell causing it to be displayed if it's evaluatable, but it's somewhat difficult for me to catch without AST code parsing. But assignment is not evaluatable; thus if you want the last line to result in output then use `eval`.

**Comment by u8sand** [comment]
Is the misplaced markdown fixed?

**Comment by u8sand** [comment]
![image](https://user-images.githubusercontent.com/1341861/79609157-3c30d500-80c4-11ea-9d5e-28a57078547c.png)

Apparently not
