### ISSUE TITLE
The progressing bar is not showing when debug=false

### ISSUE THREAD

**Issue by mjjeon** [MaayanLab/appyter#52]

**Comment by u8sand** [comment]
Not only in my environment does it work when debug is either false or true, it also works in production (see appyter website).

Can you confirm you're using the latest version and that `pip freeze | grep eventlet` returns `eventlet @ git+git://github.com/eventlet/eventlet.git@c74e867cf99bb7b9708b33a294656c4abbc0edec`?

**Comment by u8sand** [comment]
I'm assuming this is not an issue. Eventlet is being dropped in the newer version anyway so if it was still a problem it won't be pretty soon.
