### ISSUE TITLE
Unhandled output_mimetype renderer

### ISSUE THREAD

**Issue by erwinerdem** [MaayanLab/appyter#90]
I'm trying to make an appyter and it works locally.
I do however get an error.
```
Unhandled output_mimetype renderer, please report this on Appyter Issues with this information:
{"type":"output-mimetype","error":{"missing":["application/vnd.bokehjs_load.v0+json"],"data_keys":["application/javascript","application/vnd.bokehjs_load.v0+json"]}}
```
This error occurs when importing and using bokeh, but everything still works.

On a side note, could this be why my PR check on appyter-catalog is failing?

**Comment by u8sand** [comment]
This is not the case, this is kind of an internal warning for diagnosing rendering issues -- in this case it is completely harmless. Your PR issue seems to be an error in one of the imports.
